#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
#
# Adds two opencode bots — Wall-E (DeepSeek V4 Pro) + Eve (GLM-5.2) — to the
# existing `openab-claude` k3s release. Run this ON THE k3s HOST (ubuntu@openab),
# from anywhere; it cd's to its own directory. Mirrors bot-setup-opencode-kimi.md
# 附錄 C. Idempotent: safe to Ctrl-C and re-run (it re-prompts for the tokens).

TOTAL_STAGES=10

NS=cac
RELEASE=openab-claude
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BRANCH=docs/three-bot-pipeline
CHART="$SCRIPT_DIR/../../charts/openab"
DATA_BASE_DEFAULT=/data/william/openab   # static-PV host path base (see K3S.md Phase A)

# bot key : model : data-dir suffix
BOTS=(
  "walle:openrouter/deepseek/deepseek-v4-pro-0813"
  "eve:openrouter/z-ai/glm-5.2"
)

cd "$SCRIPT_DIR"

# write_secret_values <agentkey> <token> — (re)generate values-secret-<key>.yaml
write_secret_values() {
  local key="$1" token="$2" f="values-secret-$1.yaml"
  cat > "$f" <<EOF
# generated by deploy-walle-eve.sh — gitignored, never commit
agents:
  $key:
    discord:
      botToken: "$token"
EOF
  printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$f"
}

# pod_for <agentkey> — echo the running pod name for that agent (empty if none;
# always returns 0 so a bare `POD=$(pod_for x)` doesn't trip `set -e`).
pod_for() {
  kubectl -n "$NS" get pod -l "app.kubernetes.io/instance=$RELEASE" \
    -o name 2>/dev/null | grep -- "-$1-" | head -n1 || true
}

banner "Add opencode bots: Wall-E + Eve"

# ── Stage 1 ──────────────────────────────────────────────────────────────
stage "Preflight + sync repo"
say "This adds Wall-E + Eve as two more agents in the '$RELEASE' k3s release."
say "Rick / Morty / Genie / Kimi are untouched (chart hashes each agent's config"
say "separately, so their Deployments don't change and don't restart)."
note "re-running is safe: cluster actions are idempotent; you'll re-enter tokens."
for c in kubectl helm git; do
  command -v "$c" >/dev/null 2>&1 || { warn "'$c' not found on PATH — run this on the k3s host."; exit 1; }
done
[[ -d "$CHART" ]] || { warn "chart not found at $CHART — is the openab repo fully checked out?"; exit 1; }
helm -n "$NS" status "$RELEASE" >/dev/null 2>&1 || { warn "helm release '$RELEASE' not found in ns '$NS'. Deploy Kimi/Rick/Morty first."; exit 1; }
for f in values-openab-claude.yaml values-secret-claude.yaml values-openab-kimi.yaml values-secret-kimi.yaml; do
  [[ -f "$SCRIPT_DIR/$f" ]] || { warn "missing $f in $SCRIPT_DIR — needed for the helm upgrade. Bring the existing deploy's values files here first."; exit 1; }
done
ask DATA_BASE "Static-PV host path base:" ; DATA_BASE="${DATA_BASE:-$DATA_BASE_DEFAULT}"
say ""
if confirm "git -C $REPO_ROOT pull --ff-only origin $BRANCH now?"; then
  git -C "$REPO_ROOT" fetch origin "$BRANCH"
  git -C "$REPO_ROOT" checkout "$BRANCH" 2>/dev/null || git -C "$REPO_ROOT" checkout -b "$BRANCH" "origin/$BRANCH"
  git -C "$REPO_ROOT" pull --ff-only origin "$BRANCH"
  printf '  %s✓ repo on %s%s\n' "$GREEN" "$RESET" "$BRANCH"
else
  note "skipped — make sure this checkout already has Walle-/Eve-AGENTS_v2.md + the values files."
fi
pause "Enter to continue"

# ── Stage 2 ──────────────────────────────────────────────────────────────
stage "Discord app: Wall-E"
say "Create a NEW Discord application + bot for Wall-E (separate token from every"
say "other bot). The 3 target channels already exist — you're only inviting the bot."
open_url "https://discord.com/developers/applications"
step "New Application → name it 'Wall-E Dev' → Create."
step "Left nav → Bot → Reset Token → Yes, do it → Copy the token."
step "Same Bot page → Privileged Gateway Intents → turn ON 'MESSAGE CONTENT INTENT' → Save."
step "Left nav → OAuth2 → URL Generator → scopes: 'bot' → bot permissions:"
note "    View Channels · Send Messages · Read Message History · Create Public Threads · Send Messages in Threads"
step "Copy the generated URL at the bottom, open it, pick your server, Authorize."
ask_secret WALLE_TOKEN "Paste the Wall-E bot token:"
[[ -n "${WALLE_TOKEN:-}" ]] || { warn "empty token"; exit 1; }
write_secret_values walle "$WALLE_TOKEN"
pause "Enter to continue"

# ── Stage 3 ──────────────────────────────────────────────────────────────
stage "Discord app: Eve"
say "Same again, a NEW application for Eve."
open_url "https://discord.com/developers/applications"
step "New Application → 'Eve Dev' → Create."
step "Bot → Reset Token → Copy."
step "Bot → turn ON 'MESSAGE CONTENT INTENT' → Save."
step "OAuth2 → URL Generator → scope 'bot' + the same permissions as Wall-E → open URL → Authorize into your server."
ask_secret EVE_TOKEN "Paste the Eve bot token:"
[[ -n "${EVE_TOKEN:-}" ]] || { warn "empty token"; exit 1; }
write_secret_values eve "$EVE_TOKEN"
pause "Enter to continue"

# ── Stage 4 ──────────────────────────────────────────────────────────────
stage "Static PersistentVolumes"
say "One PV per bot on the node's local disk. cac-local has no provisioner, so the"
say "PV must exist before the PVC binds. claimRef pins it to '$RELEASE-<key>'."
for entry in "${BOTS[@]}"; do key="${entry%%:*}"; note "  pv-cac-$key  →  $DATA_BASE/agent-$key   (claimRef $RELEASE-$key)"; done
say ""
if confirm "create the PVs (and their host dirs) now?"; then
  for entry in "${BOTS[@]}"; do
    key="${entry%%:*}"
    mkdir -p "$DATA_BASE/agent-$key"
    kubectl apply -f - <<EOF
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cac-$key
spec:
  capacity: { storage: 20Gi }
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cac-local
  local: { path: $DATA_BASE/agent-$key }
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - { key: kubernetes.io/hostname, operator: In, values: ["openab"] }
  claimRef: { namespace: $NS, name: $RELEASE-$key }
EOF
  done
  printf '  %s✓ PVs applied%s\n' "$GREEN" "$RESET"
else
  warn "skipped — the pods will stay Pending until these PVs exist."
fi
pause "Enter to continue"

# ── Stage 5 ──────────────────────────────────────────────────────────────
stage "helm upgrade — add Wall-E + Eve"
say "Adds agents.walle + agents.eve to '$RELEASE'. Uses your local chart so the"
say "values fields always match. Existing agents' manifests won't change."
say ""
if confirm "run helm upgrade now?"; then
  helm upgrade "$RELEASE" "$CHART" -n "$NS" \
    -f values-openab-claude.yaml -f values-secret-claude.yaml \
    -f values-openab-kimi.yaml   -f values-secret-kimi.yaml \
    -f values-openab-walle.yaml  -f values-secret-walle.yaml \
    -f values-openab-eve.yaml    -f values-secret-eve.yaml
  printf '  %swaiting for rollout…%s\n' "$DIM" "$RESET"
  kubectl -n "$NS" rollout status "deploy/$RELEASE-walle" --timeout=180s || warn "walle rollout not ready — check 'kubectl -n $NS describe deploy/$RELEASE-walle'"
  kubectl -n "$NS" rollout status "deploy/$RELEASE-eve"   --timeout=180s || warn "eve rollout not ready — check 'kubectl -n $NS describe deploy/$RELEASE-eve'"
else
  warn "skipped — nothing below will work until the pods exist."
fi
pause "Enter to continue"

# ── Stage 6 ──────────────────────────────────────────────────────────────
stage "OpenRouter login (both pods)"
say "opencode stores the key in each pod's PVC (~/.local/share/opencode/auth.json),"
say "NOT in an env var. Use the SAME sk-or-v1-... key that Kimi uses."
say "This drops you into opencode's interactive login for each pod in turn:"
step "when prompted, choose 'OpenRouter' and paste the key."
for entry in "${BOTS[@]}"; do
  key="${entry%%:*}"; POD="$(pod_for "$key")"
  [[ -n "$POD" ]] || { warn "no running pod for $key — did stage 5 succeed?"; exit 1; }
  say ""; printf '  %s── %s (%s) ──%s\n' "$BOLD" "$key" "$POD" "$RESET"
  kubectl -n "$NS" exec "$POD" -- mkdir -p /home/node/.local/share/opencode /home/node/.config/opencode
  kubectl -n "$NS" exec -it "$POD" -- opencode auth login || warn "login exited non-zero for $key — re-run this stage if it didn't take"
  kubectl -n "$NS" exec "$POD" -- opencode auth list || true
done
pause "Enter to continue"

# ── Stage 7 ──────────────────────────────────────────────────────────────
stage "Model config (both pods)"
say "Write each bot's model into the GLOBAL ~/.config/opencode/opencode.jsonc —"
say "opencode's ACP server only reads the global file, not project opencode.json."
say "Also delete any project opencode.json (it would shadow the global one)."
for entry in "${BOTS[@]}"; do
  key="${entry%%:*}"; model="${entry#*:}"; POD="$(pod_for "$key")"
  [[ -n "$POD" ]] || { warn "no pod for $key"; exit 1; }
  kubectl -n "$NS" exec -i "$POD" -- sh -c 'cat > /home/node/.config/opencode/opencode.jsonc' <<EOF
{
  "\$schema": "https://opencode.ai/config.json",
  "model": "$model"
}
EOF
  kubectl -n "$NS" exec "$POD" -- rm -f /home/node/opencode.json
  printf '  %s✓ %s%s → %s\n' "$GREEN" "$RESET" "$key" "$model"
done
pause "Enter to continue"

# ── Stage 8 ──────────────────────────────────────────────────────────────
stage "GitHub login (both pods)"
say "Both bots use the single shared team account 104cac. Paste a 104cac PAT"
say "(classic or fine-grained with repo scope) — piped in with --with-token, not shown."
ask_secret GH_PAT "Paste the 104cac PAT:"
[[ -n "${GH_PAT:-}" ]] || { warn "empty PAT"; exit 1; }
for entry in "${BOTS[@]}"; do
  key="${entry%%:*}"; POD="$(pod_for "$key")"
  printf '%s' "$GH_PAT" | kubectl -n "$NS" exec -i "$POD" -- gh auth login --hostname github.com --with-token
  kubectl -n "$NS" exec "$POD" -- gh auth setup-git
  kubectl -n "$NS" exec "$POD" -- gh auth status || true
  printf '  %s✓ %s gh ready%s\n' "$GREEN" "$key" "$RESET"
done
unset GH_PAT
pause "Enter to continue"

# ── Stage 9 ──────────────────────────────────────────────────────────────
stage "Context files + restart"
say "update-context.sh writes Walle-/Eve-AGENTS_v2.md into each pod's"
say "/home/node/AGENTS.md, then we restart both so opencode reloads config + context."
if confirm "run update-context.sh + rollout restart now?"; then
  ( cd "$SCRIPT_DIR" && bash update-context.sh )
  kubectl -n "$NS" rollout restart "deploy/$RELEASE-walle" "deploy/$RELEASE-eve"
  kubectl -n "$NS" rollout status  "deploy/$RELEASE-walle" --timeout=180s || true
  kubectl -n "$NS" rollout status  "deploy/$RELEASE-eve"   --timeout=180s || true
else
  warn "skipped — bots will run with a stale/empty AGENTS.md until you run it."
fi
pause "Enter to continue"

# ── Stage 10 ─────────────────────────────────────────────────────────────
stage "Verify"
say "Each 'opencode run' below should print '> build · <the model>' and reply."
for entry in "${BOTS[@]}"; do
  key="${entry%%:*}"; model="${entry#*:}"; POD="$(pod_for "$key")"
  say ""; printf '  %s── %s (expect %s) ──%s\n' "$BOLD" "$key" "${model#openrouter/}" "$RESET"
  kubectl -n "$NS" get pod -l "app.kubernetes.io/instance=$RELEASE" | grep -- "-$key-" || true
  kubectl -n "$NS" exec "$POD" -- sh -lc 'cd /home/node && opencode run "你用哪個 model？一句話"' || warn "opencode run failed for $key"
done
say ""
step "Final check: @mention Wall-E and Eve in their Discord channel — each should reply in 中文."

finish
